# Generated by Django 3.0.4 on 2020-03-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Credits', models.CharField(max_length=10)),
                ('DefaultCredits', models.CharField(max_length=10)),
                ('Property', models.CharField(max_length=20)),
            ],
        ),
    ]
