# Generated by Django 3.0.4 on 2020-03-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegister',
            new_name='CompanyRegister',
        ),
    ]
