# Generated by Django 3.0.4 on 2020-03-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200313_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addcomp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compname', models.CharField(max_length=100, unique=True)),
                ('Credits', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HrLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=300)),
            ],
        ),
    ]
