# Generated by Django 3.0.4 on 2020-03-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_addcomp_hrlogin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addcomp',
            new_name='Compadd',
        ),
    ]
