# Generated by Django 3.0.4 on 2020-03-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Event_description', models.CharField(max_length=1000)),
                ('Event_sponsor', models.CharField(max_length=100)),
                ('Event_location', models.CharField(max_length=100)),
                ('Event_date', models.DateTimeField()),
            ],
        ),
    ]
